# netlify.toml — stable config (no lockfile required)

[build]
  # Print commit info then install+build
  command = "echo \"Commit: $(git rev-parse --short HEAD) — $(git log -1 --pretty=%s) by $(git log -1 --pretty=%an) on $(git log -1 --date=iso --pretty=%cd)\" && npm install --no-audit --no-fund && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_USE_FULL_GIT_CLONE = "true"   # ensures git history so the commit echo always works
  NODE_VERSION = "22.20.0"
