[build]
  command = """
  npx playwright install chromium \
  && npm run build \
  && npx http-server ./out -p 3000 -s & \
  npx wait-on http://localhost:3000 \
  && BASE_URL=http://localhost:3000 npm run test
  """
  publish = "out"

[build.environment]
  NODE_VERSION = "22.20.0"
  PLAYWRIGHT_BROWSERS_PATH = "0"
