[build]
  # Show short SHA and branch at the top of each build
  command = 'echo "Commit: ${COMMIT_REF:0:7} on $BRANCH" && npm run build'
  publish = ".next"

[build.environment]
  # optional, keeps behavior explicit
  NETLIFY_USE_FULL_GIT_CLONE = "false"
