[build]
  command = 'echo "Commit: $(git rev-parse --short HEAD) — $(git log -1 --pretty=%s) by $(git log -1 --pretty=%an) on $(git log -1 --pretty=%cd)" && npm run build'
  publish = ".next"

[build.environment]
  # Fetch entire history so git log and rev-parse always work
  GIT_CLONE_FLAGS = "--depth=None"
