[build]
  command = "echo \"Commit: ${COMMIT_REF:0:7} on $BRANCH\" && npm install --no-audit --no-fund && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_FULL_GIT_CLONE = "false"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
