[build]
  command = "npx playwright install --with-deps chromium && npm run build && npm run test"
  publish = "out"

[build.environment]
  NODE_VERSION = "22.20.0"
  PLAYWRIGHT_BROWSERS_PATH = "0" # store browsers in project cache
